[package]
name = "oxvba-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "oxvba-run"
path = "src/main.rs"

[dependencies]
oxvba-compiler.workspace = true
oxvba-vm.workspace = true
oxvba-jit.workspace = true
oxvba-hal.workspace = true
oxvba-runtime.workspace = true
