[package]
name = "oxvba-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxvba-com.workspace = true
oxvba-syntax.workspace = true
oxvba-ir.workspace = true
oxvba-runtime.workspace = true
thiserror.workspace = true
rkyv.workspace = true

[dev-dependencies]
oxvba-com = { workspace = true, features = ["fixture-typelibs"] }

[features]
default = []
mach_zero_copy_bytecode = []
