[package]
name = "oxvba-project"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxvba-compiler.workspace = true
oxvba-host.workspace = true
quick-xml.workspace = true
thiserror.workspace = true

[dev-dependencies]
oxvba-runtime.workspace = true
