[package]
name = "oxvba-host"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["jit"]
jit = ["dep:oxvba-jit"]

[dependencies]
oxvba-vm.workspace = true
oxvba-jit = { workspace = true, optional = true }
oxvba-compiler.workspace = true
oxvba-runtime.workspace = true
oxvba-com.workspace = true
oxvba-hal.workspace = true
thiserror.workspace = true

[dev-dependencies]
oxvba-project.workspace = true
oxvba-com = { workspace = true, features = ["fixture-typelibs"] }

[target.'cfg(target_os = "windows")'.dev-dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Variant",
] }
