[package]
name = "oxvba-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxvba-com.workspace = true
oxvba-compiler.workspace = true
oxvba-host.workspace = true
oxvba-hal.workspace = true
oxvba-project.workspace = true
oxvba-runtime.workspace = true
thiserror.workspace = true
