param(
    [string]$OutDir = "",
    [switch]$IncludeTimestampDir
)

$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$sourcesRoot = Join-Path $root "docs/spec/sources"

$urls = @(
    "https://learn.microsoft.com/en-us/openspecs/microsoft_general_purpose_programming_languages/ms-vbal/d5418146-0bd2-45eb-9c7a-fd9502722c74",
    "https://learn.microsoft.com/en-us/office/vba/api/overview/language-reference",
    "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-oaut/",
    "https://learn.microsoft.com/en-us/office/vba/language/reference/functions-visual-basic-for-applications",
    "https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/visual-basic-language-reference"
) | Select-Object -Unique

if ([string]::IsNullOrWhiteSpace($OutDir)) {
    $OutDir = Join-Path $sourcesRoot "local"
}

if ($IncludeTimestampDir) {
    $stamp = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
    $baseOutDir = $OutDir
    $OutDir = Join-Path $OutDir $stamp
}

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null

$manifestPath = Join-Path $OutDir "manifest.csv"
"url,file,sha256,bytes,fetched_utc,status,error" | Set-Content -Path $manifestPath -Encoding utf8

function Get-SafeFileName([string]$url) {
    $uri = [System.Uri]$url
    $path = $uri.AbsolutePath.Trim("/")
    if ([string]::IsNullOrWhiteSpace($path)) {
        $path = "root"
    }
    $candidate = ($uri.Host + "_" + $path.Replace("/", "_"))
    $candidate = $candidate -replace "[^A-Za-z0-9._-]", "_"
    return "$candidate.html"
}

foreach ($url in $urls) {
    $fileName = Get-SafeFileName $url
    $outFile = Join-Path $OutDir $fileName
    $status = "ok"
    $errorText = ""
    try {
        $response = Invoke-WebRequest -Uri $url -Headers @{ "User-Agent" = "OxVbaSpecSnapshot/1.0" } -MaximumRedirection 8
        [System.IO.File]::WriteAllBytes($outFile, $response.RawContentStream.ToArray())
    } catch {
        $status = "error"
        $errorText = $_.Exception.Message.Replace("`r", " ").Replace("`n", " ")
        Set-Content -Path $outFile -Value "FETCH ERROR: $errorText`nURL: $url" -Encoding utf8
    }

    $hash = (Get-FileHash -Path $outFile -Algorithm SHA256).Hash
    $bytes = (Get-Item $outFile).Length
    $utc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

    $line = '"' + $url + '","' + $fileName + '","' + $hash + '","' + $bytes + '","' + $utc + '","' + $status + '","' + ($errorText.Replace('"', '""')) + '"'
    Add-Content -Path $manifestPath -Value $line -Encoding utf8
}

$readme = @(
    '# Local Spec Snapshot',
    '',
    'Generated by `scripts/fetch-spec-sources.ps1`.',
    '',
    'Contents:',
    '- `manifest.csv`: URL -> local file mapping and checksums.',
    '- `*.html`: fetched page snapshots from primary canonical sources.',
    '',
    'Refresh command:',
    '- `pwsh -NoLogo -NoProfile -File scripts/fetch-spec-sources.ps1 -IncludeTimestampDir`'
)

Set-Content -Path (Join-Path $OutDir "README.md") -Value ($readme -join "`r`n") -Encoding utf8

if ($IncludeTimestampDir -and -not [string]::IsNullOrWhiteSpace($baseOutDir)) {
    New-Item -ItemType Directory -Path $baseOutDir -Force | Out-Null
    Set-Content -Path (Join-Path $baseOutDir "LATEST.txt") -Value $OutDir -Encoding utf8
}

Write-Host "spec-source snapshot complete: $OutDir"
