[package]
name = "oxvba-languageservice"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxvba-syntax.workspace = true
oxvba-compiler.workspace = true
oxvba-host = { workspace = true, optional = true }
oxvba-project = { workspace = true, optional = true }

[dev-dependencies]
oxvba-debug.workspace = true
oxvba-runtime.workspace = true

[features]
default = ["host-session"]
host-session = ["dep:oxvba-host", "dep:oxvba-project"]
