//! COM server DLL shim generation.

use oxvba_project::ComClassExportDescriptor;

/// Generate Rust source code for a COM server in-process DLL.
pub fn generate_com_server_shim(
    project_name: &str,
    oxb_path: &str,
    classes: &[ComClassExportDescriptor],
) -> String {
    let mut source = format!(
        r#"//! Auto-generated OxVBA COM server DLL for project "{project_name}".

#![allow(non_snake_case)]

use std::sync::OnceLock;
use std::sync::atomic::{{AtomicI32, Ordering}};

const BUNDLE_BYTES: &[u8] = include_bytes!("{oxb_path}");

static GLOBAL_REF_COUNT: AtomicI32 = AtomicI32::new(0);
static mut H_MODULE: *mut std::ffi::c_void = std::ptr::null_mut();

"#
    );

    // DllMain
    source.push_str(
        r#"#[no_mangle]
pub extern "system" fn DllMain(
    h_instance: *mut std::ffi::c_void,
    dw_reason: u32,
    _lp_reserved: *mut std::ffi::c_void,
) -> i32 {
    if dw_reason == 1 { // DLL_PROCESS_ATTACH
        unsafe { H_MODULE = h_instance; }
    }
    1 // TRUE
}

"#,
    );

    // DllGetClassObject
    source.push_str(&generate_dll_get_class_object(classes));

    // DllCanUnloadNow
    source.push_str(
        r#"
#[no_mangle]
pub extern "system" fn DllCanUnloadNow() -> i32 {
    if GLOBAL_REF_COUNT.load(Ordering::SeqCst) == 0 { 0 } else { 1 }
}

"#,
    );

    // DllRegisterServer / DllUnregisterServer
    source.push_str(
        r#"#[no_mangle]
pub extern "system" fn DllRegisterServer() -> i32 {
    // Registration logic is generated by oxvba_build::registration
    0 // S_OK
}

#[no_mangle]
pub extern "system" fn DllUnregisterServer() -> i32 {
    0 // S_OK
}
"#,
    );

    source
}

fn generate_dll_get_class_object(classes: &[ComClassExportDescriptor]) -> String {
    let mut source = String::from(
        r#"#[no_mangle]
pub extern "system" fn DllGetClassObject(
    rclsid: *const [u8; 16],
    riid: *const [u8; 16],
    ppv: *mut *mut std::ffi::c_void,
) -> i32 {
    if ppv.is_null() {
        return 0x80070057_u32 as i32; // E_INVALIDARG
    }
    unsafe { *ppv = std::ptr::null_mut(); }

"#,
    );

    for (i, class) in classes.iter().enumerate() {
        source.push_str(&format!(
            "    // Class: {} (index {i})\n",
            class.class_name
        ));
        if let Some(ref prog_id) = class.prog_id {
            source.push_str(&format!("    // ProgId: {prog_id}\n"));
        }
    }

    source.push_str(
        r#"
    0x80040111_u32 as i32 // CLASS_E_CLASSNOTAVAILABLE
}

"#,
    );
    source
}

#[cfg(test)]
mod tests {
    use super::*;
    use oxvba_project::{ComClassExportDescriptor, Instancing};

    #[test]
    fn com_server_shim_structure() {
        let classes = vec![ComClassExportDescriptor {
            class_name: "Widget".to_string(),
            prog_id: Some("TestProj.Widget".to_string()),
            instancing: Some(Instancing::MultiUse),
            description: Some("A widget".to_string()),
            members: vec![],
        }];

        let source = generate_com_server_shim("TestProj", "test.oxb", &classes);
        assert!(source.contains("DllMain"));
        assert!(source.contains("DllGetClassObject"));
        assert!(source.contains("DllCanUnloadNow"));
        assert!(source.contains("DllRegisterServer"));
        assert!(source.contains("DllUnregisterServer"));
        assert!(source.contains("Widget"));
        assert!(source.contains("TestProj.Widget"));
    }
}
